input_number:
  ix_xdrive40_charging_goal:
    name: BMW iX xDrive40 lademål
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:battery-charging-80
  ix_xdrive40_minimum_charge:
    name: BMW iX xDrive40 minimum lading
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:battery-charging-20
  ix_xdrive40_battery_capacity:
    name: BMW iX xDrive40 batterikapasitet
    min: 0
    max: 150
    step: 1
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:battery-80
  ix_xdrive40_maximum_charging_power:
    name: BMW iX xDrive40 max ladeeffekt
    min: 0
    max: 22
    step: 0.1
    mode: box
    unit_of_measurement: "kW"
    icon: mdi:ev-station
  ix_xdrive40_charging_losses:
    name: BMW iX xDrive40 ladetap
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:ev-plug-type2
  ix_xdrive40_climatize_time:
    name: BMW iX xDrive40 klimatiseringstid
    min: 0
    max: 30
    step: 1
    mode: box
    unit_of_measurement: "min"
    icon: mdi:hvac

input_boolean:
  ix_xdrive40_departure_monday:
    name: BMW iX xDrive40 avreise mandag
  ix_xdrive40_departure_tuesday:
    name: BMW iX xDrive40 avreise tirsdag
  ix_xdrive40_departure_wednesday:
    name: BMW iX xDrive40 avreise onsdag
  ix_xdrive40_departure_thursday:
    name: BMW iX xDrive40 avreise torsdag
  ix_xdrive40_departure_friday:
    name: BMW iX xDrive40 avreise fredag
  ix_xdrive40_departure_saturday:
    name: BMW iX xDrive40 avreise lørdag
  ix_xdrive40_departure_sunday:
    name: BMW iX xDrive40 avreise søndag
  ix_xdrive40_climatize_monday:
    name: BMW iX xDrive40 klimatiser mandag
  ix_xdrive40_climatize_tuesday:
    name: BMW iX xDrive40 klimatiser tirsdag
  ix_xdrive40_climatize_wednesday:
    name: BMW iX xDrive40 klimatiser onsdag
  ix_xdrive40_climatize_thursday:
    name: BMW iX xDrive40 klimatiser torsdag
  ix_xdrive40_climatize_friday:
    name: BMW iX xDrive40 klimatiser fredag
  ix_xdrive40_climatize_saturday:
    name: BMW iX xDrive40 klimatiser lørdag
  ix_xdrive40_climatize_sunday:
    name: BMW iX xDrive40 klimatiser søndag

input_datetime:
  ix_xdrive40_departure_time_monday:
    name: BMW iX xDrive40 avreisetid mandag
    has_date: false
    has_time: true
  ix_xdrive40_departure_time_tuesday:
    name: BMW iX xDrive40 avreisetid tirsdag
    has_date: false
    has_time: true
  ix_xdrive40_departure_time_wednesday:
    name: BMW iX xDrive40 avreisetid onsdag
    has_date: false
    has_time: true
  ix_xdrive40_departure_time_thursday:
    name: BMW iX xDrive40 avreisetid torsdag
    has_date: false
    has_time: true
  ix_xdrive40_departure_time_friday:
    name: BMW iX xDrive40 avreisetid fredag
    has_date: false
    has_time: true
  ix_xdrive40_departure_time_saturday:
    name: BMW iX xDrive40 avreisetid lørdag
    has_date: false
    has_time: true
  ix_xdrive40_departure_time_sunday:
    name: BMW iX xDrive40 avreisetid søndag
    has_date: false
    has_time: true

timer:
  ix_xdrive40_climatize_active:
    name: BMW iX xDrive40 klimatisering aktivert
    duration: '00:30:00'

template:
  - binary_sensor:
      - name: iX xDrive40 climatize
        unique_id: ix_xdrive40_climatize
        state: >
          {% set weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"] %}
          {% set today = now().weekday() %}
          {% set dep_time_today = states('input_datetime.ix_xdrive40_departure_time_' + weekdays[today]) %}
          {% set dep_today = states('input_boolean.ix_xdrive40_departure_' + weekdays[today]) %}
          {% set cli_today = states('input_boolean.ix_xdrive40_climatize_' + weekdays[today]) %}
          {% set tomorrow = (now().weekday()+1)%7 %}
          {% set dep_time_tomorrow = states('input_datetime.ix_xdrive40_departure_time_' + weekdays[tomorrow]) %}
          {% set dep_tomorrow = states('input_boolean.ix_xdrive40_departure_' + weekdays[tomorrow]) %}
          {% set cli_tomorrow = states('input_boolean.ix_xdrive40_climatize_' + weekdays[tomorrow]) %}
          {% set cli_time_tomorrow = (((today_at(dep_time_tomorrow) | as_timestamp) - (states('input_number.ix_xdrive40_climatize_time') | int(0))*60) | timestamp_custom('%H:%M')) %}
          {% if (dep_time_today > states('sensor.time')) %}
            {{ dep_today and cli_today }}
          {% elif cli_time_tomorrow > dep_time_tomorrow %}
            {{ dep_tomorrow and cli_tomorrow }}
          {% endif %}
        attributes:
          climatize_time: >
            {% set weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"] %}
            {% set today = now().weekday() %}
            {% set dep_time_today = states('input_datetime.ix_xdrive40_departure_time_' + weekdays[today]) %}
            {% set dep_today = states('input_boolean.ix_xdrive40_departure_' + weekdays[today]) %}
            {% set cli_today = states('input_boolean.ix_xdrive40_climatize_' + weekdays[today]) %}
            {% set cli_time_today = (((today_at(dep_time_today) | as_timestamp) - (states('input_number.ix_xdrive40_climatize_time') | int(0))*60) | timestamp_custom('%H:%M')) %}
            {% set tomorrow = (now().weekday()+1)%7 %}
            {% set dep_time_tomorrow = states('input_datetime.ix_xdrive40_departure_time_' + weekdays[tomorrow]) %}
            {% set dep_tomorrow = states('input_boolean.ix_xdrive40_departure_' + weekdays[tomorrow]) %}
            {% set cli_tomorrow = states('input_boolean.ix_xdrive40_climatize_' + weekdays[tomorrow]) %}
            {% set cli_time_tomorrow = (((today_at(dep_time_tomorrow) | as_timestamp) - (states('input_number.ix_xdrive40_climatize_time') | int(0))*60) | timestamp_custom('%H:%M')) %}
            {% if (dep_time_today > states('sensor.time')) %}
              {{ cli_time_today }}
            {% else %}
              {{ cli_time_tomorrow }}
            {% endif %}
          departure_time: >
            {% set weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"] %}
            {% set today = now().weekday() %}
            {% set dep_time_today = states('input_datetime.ix_xdrive40_departure_time_' + weekdays[today]) %}
            {% set dep_today = states('input_boolean.ix_xdrive40_departure_' + weekdays[today]) %}
            {% set tomorrow = (now().weekday()+1)%7 %}
            {% set dep_time_tomorrow = states('input_datetime.ix_xdrive40_departure_time_' + weekdays[tomorrow]) %}
            {% set dep_tomorrow = states('input_boolean.ix_xdrive40_departure_' + weekdays[tomorrow]) %}
            {% if (dep_time_today > states('sensor.time')) %}
              {{ dep_time_today }}
            {% else %}
              {{ dep_time_tomorrow }}
            {% endif %}

automation:
  - id: ix_xdrive40_start_climatizing
    alias: BMW iX xDrive40 start climatizing
    trigger:
      - platform: template
        value_template: >
          {{ (state_attr('binary_sensor.ix_xdrive40_climatize', 'climatize_time') <= states('sensor.time')) and 
             (state_attr('binary_sensor.ix_xdrive40_climatize', 'departure_time') >= states('sensor.time')) and
             is_state('binary_sensor.ix_xdrive40_climatize','on') and
             not(is_state('timer.ix_xdrive40_climatize_active','active')) }}
    action:
      - service: timer.start
        target:
          entity_id: timer.ix_xdrive40_climatize_active
      - service: button.press
        data: {}
        target:
          entity_id: button.ix_xdrive40_activate_air_conditioning
